---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # CentOS    
  - name: CentOS-8
    image: "geerlingguy/docker-centos8-ansible:latest"
    command: "/usr/lib/systemd/systemd"
    environment: { container: docker }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    privileged: true
    pre_build_image: true
    
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    #- verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8